name: Coolify Deploy + Verify

on:
  workflow_call:
    inputs:
      health_url:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      coolify_webhook:
        required: true
      coolify_token:
        required: true

jobs:
  deploy-verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - run: echo "perm test"
